### ISSUE TITLE
Cypress test workflows

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco-CMS#11305]
This issue is for maintaining a list of things that needs Cypress tests.

### Users

- [x] - Create a user
- [x] - Update a user - PR submitted #11270
- [x] - Delete a user - PR submitted #11282

### Languages

- [ ] - Create a language - PR submitted #11546 
- [ ] - Update a language - PR submitted #11333
- [ ] - Delete a language - PR submitted #11380
- [ ] - Choose another default language, does it change the UI?

### Data Types

**Comment by umbrabot** [comment]
Hiya @jemayn,

Just wanted to let you know that we noticed that this issue got a bit stale and might not be relevant any more.

We will close this issue for now but we're happy to open it up again if you think it's still relevant (for example: it's a feature request that's not yet implemented, or it's a bug that's not yet been fixed). 

To open it this issue up again, you can write `@umbrabot still relevant` in  a new comment as the first line. It would be *super* helpful for us if on the next line you could let us know why you think it's still relevant.

For example:

>@umbrabot still relevant
>This bug can still be reproduced in version `x.y.z` 

This will reopen the issue in the next few hours.

Thanks, from your friendly Umbraco GitHub bot :robot: :slightly_smiling_face:
