### ISSUE TITLE
Start decoupling from AngularJs

### ISSUE THREAD

**Issue by nathanwoulfe** [umbraco/Umbraco-CMS#7718]
Might be controversial, but here we go...

I'm proposing we start refining the backoffice javascript to remove/reduce the coupling to AngularJs. The quickest win here (IMO) is to remove all usages of [Angular functions](https://docs.angularjs.org/api/ng/function).

Most (if not all) of these exist as native JS methods in ES6, or are provided in Lodash. Umbraco currently takes a dependency on Underscore, of which Lodash is a superset. Benefit of Lodash is that it allows individual functions to be included, greatly reducing the size of the dependency. I don't see any issue in replacing a framework dependency with a library dependency.

So I guess this is two-fold - replace AngularJs fns with vanilla JS where possible, else import the appropriate Lodash method. At the same time, replace Underscore with vanilla, falling back to Lodash.

Why? It will need to happen eventually. Regardless of what direction the backoffice takes, the AngularJs functions will stop working. These changes can be addressed now as incremental improvements rather than leaving until later as part of sweeping backoffice changes.

## TODO:

- [x] add utility javascript bits - resolved in #7738, updated in #7975, #8014 
- [x] replace instances of angular.noop() - PR #7738 
- [x] replace instances of angular.copy() - PR #7950
- [x] replace instances of angular.isFunction() - PR #7861
- [x] replace instances of angular.element() - PR #7951 
- [x] replace instances of angular.equals() - PR #7860
- [ ] replace instances of angular.extend()
- [x] replace instances of angular.forEach() - PR #7928
- [x] replace instances of angular.fromJson() - PR #7952
- [x] replace instances of angular.isArray() - PR #7934 
- [x] replace instances of angular.isDefined() - PR #7927
- [x] replace instances of angular.isNumber() - PR #7925
- [x] replace instances of angular.isObject() - PR #7931
- [x] replace instances of angular.isString() - PR#7929
- [x] replace instances of angular.isUndefined() - PR #7856 
- [x] replace instances of angular.toJson() - PR #7924
- [ ] profit!

**Comment by anthonydotnet** [comment]
Agree. 

These are quick wins.

**Comment by c9mbundy** [comment]
I'll be even more controversial... migrate angularjs to vuejs - for which the above is a compatible step of an increment migration process.  :scream:

**Comment by nathanwoulfe** [comment]
@c9mbundy even mentioning an alternate framework is waaaay out of scope for what I want to do here - these changes would be part of the required groundwork for shifting the backoffice to Vue, React, AngularX, JsDuJour * etc. 

Really want this to be a completely stack agnostic conversation, focus on cleaning up/improving where possible to best facilitate whatever migration happens in future

* this does not exist. Yet. Consider this me staking my claim to the name!

**Comment by pgregorynz** [comment]
Agree with this.

The less framework dependency the better.

**Comment by giuunit** [comment]
Agree with this. Slowly removing framework dependencies is the only way forward

**Comment by dawoe** [comment]
Hi @nathanwoulfe 

Same can be done for the usage of underscore.js. A lot of the functions in there are native as well.

Dave

**Comment by nathanwoulfe** [comment]
@dawoe I know there's no native deep copy (lodash provides that) but outside of that, I think most everything is available native

**Comment by dawoe** [comment]
As I understand the clone function from underscore is not a deep clone : https://underscorejs.org/#clone

I always use [angular.copy](https://docs.angularjs.org/api/ng/function/angular.copy) for that

Dave

**Comment by nielslyngsoe** [comment]
Hi @nathanwoulfe 
This is great, and it's a great step towards moving forward.

Here are a few perspectives of why we think its right:
- We are not ready or suited to write completely new code for BackOffice today.
- Therefore we need to bring existing code up to speed.
- We do know we need to get rid of AngularJS.
- We do know that we want to be as little framework/library dependent in the future.
- We do know we have a lot of code that could be using native technology instead of the framework/library.
- And we do know we need to move forward in minor steps, to avoid making a mess and rapidly begin able to release stable versions.

I think you wrote a perfect description of the first goal for this journey:

> Replace AngularJs functions with vanilla JS where possible, else import the appropriate Lodash method. At the same time, replace Underscore with vanilla, falling back to Lodash.

Feel free to get started, I would love to see a few minor PRs to ensure that we agree on the path. And afterward this could go for full-speed with up-for-grabs issues etc.

**Comment by anthonydotnet** [comment]
This is a great initiative.

Now all we need is the blessing from HQ, and a few hackathons.

Then in a year we can discuss what ever hipster JS framework is around.

**Comment by nul800sebastiaan** [comment]
And just to set some expectations; we don't have anyone dedicated to "new hipster JS framework" at the moment. The work resulting from this will be processed by the ~PR Team~ Core Collaborator team and it's easiest if this is happening in small PRs. The priority for evaluating incoming PRs is on fixing current bugs first.

And while I do love some good cleanup work, it's dangerous, due to lack of automated testing, so unit tests will help a lot in making getting changes evaluated and merged more quickly.

**Comment by nul800sebastiaan** [comment]
Last note: while this is `up-for-grabs`, this issue will not be "fixed" by a single PR. It would be good if @nathanwoulfe kicks of with a few trial PRs and then to come up with a list of items that need improvement, so that other people can pick up various smaller bits to improve. 

Please organize this so that the work is easy to share among a few people. 
For inspiration, the accessibility team is really good at making a list of stuff like that: https://github.com/umbraco/Umbraco-CMS/issues/5277

**Comment by umbrabot** [comment]
Hi @nathanwoulfe,

We're writing to let you know that we've added the `Up For Grabs` label to your issue. We feel that this issue is ideal to flag for a community member to work on it. Once flagged here, folk looking for issues to work on will know to look at yours. Of course, please feel free work on this yourself ;-).  If there are any changes to this status, we'll be sure to let you know. 

For more information about issues and states, have a look at [this blog post](https://umbraco.com/blog/the-umbraco-issue-tracker-process/)

Thanks muchly, from your friendly PR team bot :-)

**Comment by markadrake** [comment]
- We absolutely should replace what we can, code that is dependent on a specific framework or library, when native browser APIs can replace them.
- Huge resounding H5YR for catching the potential savings LoDash offers. 
- Is there an opportunity to introduce tree-shaking? (Webpack? Parcel? Something else?)
- Where browser adoption isn't the greatest, if we aren't already, there's no shame in using _polyfills_ – or better yet _ponyfills_.
- If Babel is not already part of the build process for the frontend (I am embarrassed for not knowing) it should be, and it would allow for us to write modern JavaScript and target a set of browsers for compatibility.

Just some thoughts as I read through this.

**Comment by PeteDuncanson** [comment]
Wow. I'm excited to see this one get raised and get such a good reception. Bravo Nathan.

Small units of work would be the order of the day if we wanted to get this in pulled in. In my mind it would be super tiny changes per file (maybe even per method if its a big file to change) so that the CC team can easily eye ball it and pull it in. Plus if the changes are small enough you can get a few done in a lunch break and feel like you've achieved something and its gets HQ's PR count up so they can shout about that, win/win ;)

Testing is always lovely but its also difficult to create tests for some of the existing stuff the way its written (which is one of the reasons its not been done as yet). I think we would need someone brave to do a bit of a sprint into how best to do the testing and then show an example that others can follow. I don't think it should be a requirement though (swapping out one forEach implementation for another shouldn't require a test in my mind), but encouraged if possible.

For completeness for those that are hearing about work on tweaking the back office here are some of the older issues that contain lots of thoughts/ideas/plans on whatever we can do to polish up whats already there and get it in a fit state:

https://github.com/umbraco/Umbraco-CMS/issues/4913 
https://github.com/umbraco/Umbraco-CMS/issues/4875
https://github.com/umbraco/Umbraco-CMS/issues/4875
https://github.com/umbraco/Umbraco-CMS/issues/4804
https://github.com/umbraco/Umbraco-CMS/issues/4872

and the dreaded "Get TypeScript into the back office" thread https://github.com/umbraco/Umbraco-CMS/issues/5215

**Comment by cssquirrel** [comment]
Agree with all the agreeing. ;)

As has been already said, regardless of the backoffice's future form, it will definitely part ways from AngularJS at some point. This feels like a real approach to making an actual start to the process. Which is fantastic.

**Comment by protherj** [comment]
#h5yr @nathanwoulfe, sounds like an excellent step to take.

**Comment by nathanwoulfe** [comment]
Given this was a whole lot less controversial than I might have thought, I'm happy to take a lead on kicking off the work. Will follow the A11Y team's lead and go for a Trello board to manage work.

First though, will do some proper analysis of how much work is involved, where the quick-wins are hiding, and changes that may still require Lodash. From that, can map out a plan in Trello and away we go. Easy. Simple. 😃 

More than happy to talk further about how to approach the work - by file, by function, by module etc.

**Comment by nathanwoulfe** [comment]
[Trello board](https://trello.com/invite/b/wiDsUbly/7889d5af96f4fd8a186910f2b6024f43/umbracos-angularjs-divorce) for anyone interested. Feel free to add/change/move stuff. I'm not a PM.

**Comment by ronaldbarendse** [comment]
While I absolutely agree we should get ready for a client-side framework transition (especially because the [AngularJS LTS period ends on June 30, 2021](https://docs.angularjs.org/misc/version-support-status#long-term-support)), I'm a little sceptical whether any of these code changes will eventually be part of the new codebase and/or add any real value.

Sure, it doesn't hurt to rewrite some JS functions and having additional tests would be great, but I think that time would be better spend in converting existing code to TypeScript (as @PeteDuncanson linked in his comment). That has the potential to reduce/prevent a lot of bugs, make testing easier and while doing so, also swap out a lot of these functions at the same time!

**Comment by nathanwoulfe** [comment]
@ronaldbarendse as much as I'm on board with a TS migration, that's an order of magnitude more work than getting these changes done. Regardless of where the backoffice goes in terms of framework/language, these changes will need to be made, so no time like the present. 

Sure, some/all of this may be removed in the future, but until that happens, it's still an incremental improvement to reduce the coupling to AngularJs.

**Comment by anthonydotnet** [comment]
Agree. In order to TypeScript the code, we need the code to actually be written in JS. Currently it's full of legacy AngularJS functions. You can't TypeScript those.

Moving to as much vanilla JS as possible is the first step to actually using TypeScript.

**Comment by nielslyngsoe** [comment]
I think everyone is in for a TypeScript codebase. But I would say that we first need to make sure that we are in a good state for implementing TypeScript.

I would love to see us making an effort to decouple things as the main focus. Just like Nathan now proposed getting rid of utility functions from AngularJS.
The next step could be moving Services out of AngularJS and splitting some services up to minor, or just turning some functionality into functions. And in this process, it could make sense to convert to TypeScript as well. But I think we are better of not focusing on TypeScript as the goal but focusing on decoupling. Ensuring that our architecture becomes SOLID, or at least closer to those concepts.

**Comment by MMasey** [comment]
PR for `isString` #7929

**Comment by MMasey** [comment]
PR for `isArray` #7934

**Comment by liamlaverty** [comment]
PR for `equals` and some other utilities used by `equals` can be found here #7975

**Comment by bjarnef** [comment]
PR for `fromJson` https://github.com/umbraco/Umbraco-CMS/pull/8014 has been merged to `v8/dev` but is missing to be included in `v8/contrib`.

The replacement of `angular.fromJson` with `JSON.parse` in https://github.com/umbraco/Umbraco-CMS/pull/7952 was breaking a few things in core since `angular.fromJson` also checked is value was a string before doing `JSON.parse`.

Since the Utilities already had the `toJson` I think it should also have this `fromJson` function.

**Comment by kjac** [comment]
Bit more work on replacing angular.forEach in #8501

**Comment by kjac** [comment]
And more angular.forEach replacement in #8505

**Comment by nathanwoulfe** [comment]
@kjac lovely stuff! I've picked up some similar changes from an issue @warrenbuckley created a while back re removing underscore, so have been chipping away at killing off _.each. Long story short hopefully we don't step on each other's toes. 

I'll link the PRs here when I'm not on my phone. Thinking maybe a parent issue to link the angular and underscore stuff might be useful too

**Comment by kjac** [comment]
@nathanwoulfe I saw the PRs - #8475 and #8490 ... I think we're good 👍 the _.each-removal doesn't seem to interfere much if at all with the angular.forEach removal. And if it does, well... it should be merge-able for sure.

**Comment by nathanwoulfe** [comment]
@kjac sounds good to me 👍👍

**Comment by kjac** [comment]
#8538 contains angular.forEach replacement for the remaining property editors.

**Comment by kjac** [comment]
#8552 contains angular.forEach replacement for filters and services

**Comment by emma-hq** [comment]
Aw this issue!!! I love it. Brings back some nice memories from last year and we all know they're in short supply. We have only one more to do and then PROFIT! 😆 

Anyone from this team want to pick up .extend()? Go on. Go on go on go on go on go on.

Em

**Comment by bjarnef** [comment]
@emma-hq I couldn't find an open PR to replace `angular.extend()` so I have submitted a PR here: https://github.com/umbraco/Umbraco-CMS/pull/10023 😁 👍

**Comment by emma-hq** [comment]
Aw thank you @bjarnef - you're a ⭐

**Comment by nathanwoulfe** [comment]
CLOSED! Finally!

Thanks to all who contributed PRs/thoughts/prayers 😄

**Comment by nathanwoulfe** [comment]
#10759 resolves some sneaky angular.forEach usages which managed to weasel their way back in
